# baseURL = 'https://elderlyaugustus.github.io/'
# languageCode = 'en-us'
# title = '''xa's blog'''
# theme = "PaperModX"
# # disqusShortname = 'xa'   # add disqus comments
# paginate = 5
# enableInlineShortcodes = true
# enableRobotsTXT = true
# buildDrafts = false
# buildFuture = false
# buildExpired = false
# enableEmoji = true

baseURL = "https://elderlyaugustus.github.io/"
# relativeURLs = true
# uglyURLs = true
title = '''xα's blog'''
paginate = 10
theme = "PaperModX"
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = true
buildFuture = false
buildExpired = false
enableEmoji = true

# [params]
#   mainSections = [ "docs", "posts" ]
#   disableAnchoredHeadings = true
#   images = [ "cover.png" ]
#   DateFormat = "2006-01-02"
#   useCustomAnalytics = true
#   defaultTheme = "auto"
#   # ShowShareButtons = true
#   # ShowReadingTime = true
#   # ShowWordCount = true
#   displayFullLangName = true
#   ShowPostNavLinks = true
#   ShowBreadCrumbs = true
#   ShowCodeCopyButtons = true
#   ShowToc = true
#   TocOpen = true
#   TocSide = "right"
#   EnableInstantClick = true
#   EnableImageZoom = true



[params]
  math = true
  
  env = "production"
  description = '''xα's blog'''
  author = [ "xα" ]
  mainSections = [ "posts" ]
  disableAnchoredHeadings = true
  images = [ "cover.png" ]
  DateFormat = "2006-01-02"
  # useCustomAnalytics = true
  defaultTheme = "auto"
  ShowShareButtons = true
  # ShowReadingTime = true
  # ShowWordCount = true
  displayFullLangName = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = true
  TocSide = "right"
  EnableInstantClick = true
  EnableImageZoom = true

  [params.assets]
    disableFingerprinting = true

  # [params.commentSystems.disqus]
  #   shortname = "xa"

  # [params.commentSystems.remark42]
  #   url = "https://remark42.reorx.com"
  #   site = "reorx.github.io"

  # [params.commentSystems.telegramWidget]
  #   channel = "reorx_share"
  #   accentColor = "9077e1"
  #   limit = 20

  # [params.defaultCommentSystems]
  #   remark42 = true

  # [params.profileMode]
  #   enabled = false
  #   title = "xα"
  #   imageUrl = "#"
  #   imageTitle = "xa image"

  #   [[params.profileMode.buttons]]
  #     name = "Archives"
  #     url = "/archives/"

  #   [[params.profileMode.buttons]]
  #     name = "Tags"
  #     url = "/tags/"

  [params.homeInfoParams]
    # Title = "xα"
    Content = '''<link rel="preload stylesheet" as=style href=css/main.min.css>
    <div class="-mt-4 mb-20 flex items-start">
    <div class="mr-5 shrink-0 rounded-full border-[0.5px] border-black/10 bg-white/50 p-3 shadow-xl dark:bg-white/80">
    <img class="my-0 h-14 w-14 rounded-full !bg-black/5 hover:animate-spin dark:!bg-black/80" src="icons/xa_blog.png" alt="xa.png">
    </div>
    <div>
    <h1 class="mt-1.5 mb-3 text-3xl font-bold">xα</h1>
    <div class="break-words">
    游戏引擎研发，技术美术
    </div>
    </div>
    </div>
    欢迎访问我的个人主页，将来一定会有更多知识分享的！（画饼
    '''

  [[params.socialIcons]]
    name = "github-simple"
    url = "https://github.com/ElderlyAugustus/ElderlyAugustus.github.io"

  [params.editPost]
    URL = "https://github.com/ElderlyAugustus/ElderlyAugustus.github.io/content"
    Text = "Suggest Changes"
    appendFilePath = true

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'dracula'
    lineNos = false
    noClasses = false

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 10
  [[menu.main]]
    identifier = "archive"
    name = "Archives"
    url = "/archives/"
    weight = 10
  # [[menu.main]]
  #   identifier = "categories"
  #   name = "Categories"
  #   url = "/categories/"
  #   weight = 10
  # [[menu.main]]
  #   identifier = "series"
  #   name = "Series"
  #   url = "/series/"
  #   weight = 10

[minify]
  disableXML = true

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^pandoc$', '^nvim$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

  [security.funcs]
    getenv = ['^HUGO_']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']